import streamlit as st

st.set_page_config(page_title="Marketing Personalization Survey", page_icon="📢")

# page 1: survey introduction

st.title("Marketing Personalization Survey")
st.markdown("""
        ### About the Researcher  
    Hi! My name is Jenna Huang, and I am conducting this project as part of my independent research work.
    If you have any questions, feel free to contact me at jennaaahuang09@gmail.com.

    ### Purpose of the Study  
    The purpose of this study is to understand how people perceive different types of personalized advertisements.  
    Specifically, I am studying how varying levels of personalization affect how ads are perceived in terms of:  
    - **Relevance** 
    - **Creepiness** (how unsettling the ad feels)  
    - **Likelihood of engaging**  
    - **Purchase intention**  

    ### What Participation Involves  
    If you participate, you will:  
    - Provide some basic information (first name, age, city, and gender).  
    - View 15 advertisements that are **AI-generated** using your information.  
    - Rate each ad on the four criteria listed above.  
      
    This should take about **10 minutes**.  

    ### Risks  
    - Some ads may feel uncomfortably personal because they are generated using your details.  
    - Since ads are generated by AI, there is a small chance they may contain unexpected or inappropriate language.  
    - Please note that **I am not responsible for the exact wording of AI-generated ads.**  

    ### Benefits   
    - While there may not be direct personal benefits, your participation will help researchers better understand how personalized advertising is perceived, which could inform future marketing practices and improve user experience.


    ### Confidentiality  
    - All responses are **kept confidential**.   
    - Data will only be accessible by the primary researcher, and will be deleted after.  
    - Any publications or reports will only include **anonymized and aggregated data**.  

    ### Important Notes  
    - You must be **18 years or older** to participate.  
    - Participation is voluntary.  
    """)
    